Lab4: unit-test for isvalidvalue method
jvillemare/CISC181-Sudoku pull request #11
Opened 2019-04-20 20:45 UTC by YisiYin

2019-04-21 03:04 UTC, jvillemare approved these changes
Most of the structure and function of a good unit tests for your assigned tests. Too tired for quality control.

2019-04-21 03:04 UTC, jvillemare commented on src/test/java/pkgGame/SudokuTest.java
> +			assertTrue((Boolean)mIsValidValue.invoke(s, 2) == true);
`isValidValue` is expecting it's first parameter to be a `Sudoku.Cell`, not a `Sudoku` object.

2019-04-21 03:04 UTC, jvillemare commented on src/test/java/pkgGame/SudokuTest.java
> +			mSetCells.invoke(s, null);
Same problem as directly above.

2019-04-21 03:04 UTC, jvillemare commented on src/test/java/pkgGame/SudokuTest.java
> +		// TODO: Aris will do this...
Yep.

2019-04-22 18:20 UTC, YisiYin commented
Hi James, I have fixed my code, Could you help me to check my code?

James Villemarette <notifications@github.com> 于2019年4月20日周六 下午11:04写道：

> *@jvillemare* approved this pull request.
>
> Most of the structure and function of a good unit tests for your assigned
> tests. Too tired for quality control.
> ------------------------------
>
> In src/test/java/pkgGame/SudokuTest.java
> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#discussion_r277152504>
> :
>
> > +				{ 8, 0, 0, 0, 6, 0, 0, 0, 3 }, { 4, 0, 0, 8, 0, 3, 0, 0, 1 }, { 7, 0, 0, 0, 2, 0, 0, 0, 6 },
> +				{ 0, 6, 0, 0, 0, 0, 2, 8, 0 }, { 0, 0, 0, 4, 1, 9, 0, 0, 5 }, { 0, 0, 0, 0, 8, 0, 0, 7, 9 } };
> +		Sudoku s;
> +		
> +		try {
> +			Class<?> c = Class.forName("pkgGame.Sudoku");
> +			Constructor constructor = c.getConstructor(new Class[] { int[][].class });
> +			constructor.setAccessible(true);
> +			s = (Sudoku) constructor.newInstance(puzzle);
> +			
> +			Method mSetCells = c.getDeclaredMethod("setCells", new Class[] { int.class });
> +			Method mIsValidValue = c.getDeclaredMethod("isValidValue", new Class[] { int.class });
> +			
> +			mSetCells.invoke(s, null);
> +			
> +			assertTrue((Boolean)mIsValidValue.invoke(s, 2) == true);
>
> isValidValue is expecting it's first parameter to be a Sudoku.Cell, not a
> Sudoku object.
> ------------------------------
>
> In src/test/java/pkgGame/SudokuTest.java
> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#discussion_r277152510>
> :
>
> >  		
> -		//assertTrue(...);
> +		try {
> +			Class<?> c = Class.forName("pkgGame.Sudoku");
> +			Constructor constructor = c.getConstructor(new Class[] { int[][].class });
> +			constructor.setAccessible(true);
> +			s = (Sudoku) constructor.newInstance(puzzle);
> +			
> +			Method mSetCells = c.getDeclaredMethod("setCells", new Class[] { int.class });
> +			Method mIsValidValue = c.getDeclaredMethod("isValidValue", new Class[] { int.class });
> +			
> +			mSetCells.invoke(s, null);
>
> Same problem as directly above.
> ------------------------------
>
> In src/test/java/pkgGame/SudokuTest.java
> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#discussion_r277152519>
> :
>
> > @@ -125,7 +205,7 @@ public void Cell_hashCode_Test() throws Exception {
>  	@Test
>  	public void Cell_equals_Test() throws Exception {
>  		
> -		// TODO: Yisi will do this...
> +		// TODO: Aris will do this...
>
> Yep.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#pullrequestreview-228897246>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALNHR7U6NWKVR42ZYBZF6W3PRPKSJANCNFSM4HHKMNKA>
> .
>

2019-04-22 20:02 UTC, jvillemare commented
@YisiYin, I will be able to review your code within the hour. Please wait until then.

2019-04-22 22:52 UTC, jvillemare requested changes
Apply changes for both unit tests.

2019-04-22 22:52 UTC, jvillemare commented on src/test/java/pkgGame/SudokuTest.java
>  			s = (Sudoku) constructor.newInstance(puzzle);
The cast of `(Sudoku)` should be `(Sudoku.Cell)`.

2019-04-22 22:52 UTC, jvillemare commented on src/test/java/pkgGame/SudokuTest.java
> +			mSetCells.invoke(c, null);
This should remain `s` instead of changing it to the variable `c`. You can't invoke from the context of a constructor.

2019-04-23 01:53 UTC, jvillemare approved these changes

2019-04-23 01:53 UTC, jvillemare commented
Accepting changes because @YisiYin did not implement appropriate changes, and lab deadline is now less than 3 hours.

2019-04-23 01:53 UTC, merged

2019-04-23 02:01 UTC, YisiYin commented
Hi James. If I change the cast of (Sudoku) to (Sudoku.Cell), it has an
error.

James Villemarette <notifications@github.com> 于2019年4月22日周一 下午6:52写道：

> *@jvillemare* requested changes on this pull request.
>
> Apply changes for both unit tests.
> ------------------------------
>
> In src/test/java/pkgGame/SudokuTest.java
> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#discussion_r277464960>
> :
>
> > @@ -81,15 +81,15 @@ public void isValidValue_Test2() throws Exception {
>  		Sudoku s;
>  		
>  		try {
> -			Class<?> c = Class.forName("pkgGame.Sudoku");
> +			Class<?> c = Class.forName("pkgGame.Sudoku.Cell");
>  			Constructor constructor = c.getConstructor(new Class[] { int[][].class });
>  			constructor.setAccessible(true);
>  			s = (Sudoku) constructor.newInstance(puzzle);
>
> The cast of (Sudoku) should be (Sudoku.Cell).
> ------------------------------
>
> In src/test/java/pkgGame/SudokuTest.java
> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#discussion_r277465064>
> :
>
> >  			Constructor constructor = c.getConstructor(new Class[] { int[][].class });
>  			constructor.setAccessible(true);
>  			s = (Sudoku) constructor.newInstance(puzzle);
>  			
>  			Method mSetCells = c.getDeclaredMethod("setCells", new Class[] { int.class });
>  			Method mIsValidValue = c.getDeclaredMethod("isValidValue", new Class[] { int.class });
>  			
> -			mSetCells.invoke(s, null);
> +			mSetCells.invoke(c, null);
>
> This should remain s instead of changing it to the variable c. You can't
> invoke from the context of a constructor.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#pullrequestreview-229284553>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALNHR7X2FN35AEZQZGMV3DTPRY6R3ANCNFSM4HHKMNKA>
> .
>

2019-04-23 02:49 UTC, YisiYin commented
Hi, I have a problem to commit the code. It shows like that:
[image: image.png]


Yisi Yin <yinyisi@udel.edu> 于2019年4月22日周一 下午10:01写道：

> Hi James. If I change the cast of (Sudoku) to (Sudoku.Cell), it has an
> error.
>
> James Villemarette <notifications@github.com> 于2019年4月22日周一 下午6:52写道：
>
>> *@jvillemare* requested changes on this pull request.
>>
>> Apply changes for both unit tests.
>> ------------------------------
>>
>> In src/test/java/pkgGame/SudokuTest.java
>> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#discussion_r277464960>
>> :
>>
>> > @@ -81,15 +81,15 @@ public void isValidValue_Test2() throws Exception {
>>  		Sudoku s;
>>  		
>>  		try {
>> -			Class<?> c = Class.forName("pkgGame.Sudoku");
>> +			Class<?> c = Class.forName("pkgGame.Sudoku.Cell");
>>  			Constructor constructor = c.getConstructor(new Class[] { int[][].class });
>>  			constructor.setAccessible(true);
>>  			s = (Sudoku) constructor.newInstance(puzzle);
>>
>> The cast of (Sudoku) should be (Sudoku.Cell).
>> ------------------------------
>>
>> In src/test/java/pkgGame/SudokuTest.java
>> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#discussion_r277465064>
>> :
>>
>> >  			Constructor constructor = c.getConstructor(new Class[] { int[][].class });
>>  			constructor.setAccessible(true);
>>  			s = (Sudoku) constructor.newInstance(puzzle);
>>  			
>>  			Method mSetCells = c.getDeclaredMethod("setCells", new Class[] { int.class });
>>  			Method mIsValidValue = c.getDeclaredMethod("isValidValue", new Class[] { int.class });
>>  			
>> -			mSetCells.invoke(s, null);
>> +			mSetCells.invoke(c, null);
>>
>> This should remain s instead of changing it to the variable c. You can't
>> invoke from the context of a constructor.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#pullrequestreview-229284553>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/ALNHR7X2FN35AEZQZGMV3DTPRY6R3ANCNFSM4HHKMNKA>
>> .
>>
>

2019-04-23 03:42 UTC, YisiYin commented
Hi James, I fixed my code, but I can't commit to the GitHub for the same
reasons in the terminal. I am sorry I have no idea for that.

Yisi Yin <yinyisi@udel.edu> 于2019年4月22日周一 下午10:49写道：

> Hi, I have a problem to commit the code. It shows like that:
> [image: image.png]
>
>
> Yisi Yin <yinyisi@udel.edu> 于2019年4月22日周一 下午10:01写道：
>
>> Hi James. If I change the cast of (Sudoku) to (Sudoku.Cell), it has an
>> error.
>>
>> James Villemarette <notifications@github.com> 于2019年4月22日周一 下午6:52写道：
>>
>>> *@jvillemare* requested changes on this pull request.
>>>
>>> Apply changes for both unit tests.
>>> ------------------------------
>>>
>>> In src/test/java/pkgGame/SudokuTest.java
>>> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#discussion_r277464960>
>>> :
>>>
>>> > @@ -81,15 +81,15 @@ public void isValidValue_Test2() throws Exception {
>>>  		Sudoku s;
>>>  		
>>>  		try {
>>> -			Class<?> c = Class.forName("pkgGame.Sudoku");
>>> +			Class<?> c = Class.forName("pkgGame.Sudoku.Cell");
>>>  			Constructor constructor = c.getConstructor(new Class[] { int[][].class });
>>>  			constructor.setAccessible(true);
>>>  			s = (Sudoku) constructor.newInstance(puzzle);
>>>
>>> The cast of (Sudoku) should be (Sudoku.Cell).
>>> ------------------------------
>>>
>>> In src/test/java/pkgGame/SudokuTest.java
>>> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#discussion_r277465064>
>>> :
>>>
>>> >  			Constructor constructor = c.getConstructor(new Class[] { int[][].class });
>>>  			constructor.setAccessible(true);
>>>  			s = (Sudoku) constructor.newInstance(puzzle);
>>>  			
>>>  			Method mSetCells = c.getDeclaredMethod("setCells", new Class[] { int.class });
>>>  			Method mIsValidValue = c.getDeclaredMethod("isValidValue", new Class[] { int.class });
>>>  			
>>> -			mSetCells.invoke(s, null);
>>> +			mSetCells.invoke(c, null);
>>>
>>> This should remain s instead of changing it to the variable c. You
>>> can't invoke from the context of a constructor.
>>>
>>> —
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/jvillemare/CISC181-Sudoku/pull/11#pullrequestreview-229284553>,
>>> or mute the thread
>>> <https://github.com/notifications/unsubscribe-auth/ALNHR7X2FN35AEZQZGMV3DTPRY6R3ANCNFSM4HHKMNKA>
>>> .
>>>
>>